language: python
python:
- '2.7'
services:
- redis-server
addons:
  postgresql: '9.3'
sudo: false
cache:
  directories:
  - $HOME/.cache/pip
install:
- pip install --upgrade pip
- pip install -r pip-freeze.txt --upgrade
- pip install coveralls
- npm install
before_script:
- psql -U postgres -c "CREATE USER temba WITH PASSWORD 'temba';"
- psql -U postgres -c "ALTER ROLE temba WITH SUPERUSER;"
- psql -d 'template1' -U postgres -c "CREATE EXTENSION postgis;"
- psql -d 'template1' -U postgres -c "CREATE EXTENSION postgis_topology;"
- psql -d 'template1' -U postgres -c "CREATE EXTENSION hstore;"
- psql -U temba postgres -c "CREATE DATABASE temba;"
- ln -s $TRAVIS_BUILD_DIR/temba/settings.py.dev $TRAVIS_BUILD_DIR/temba/settings.py
script:
- node_modules/karma/bin/karma start karma.conf.coffee --single-run --browsers PhantomJS
- coverage run --source="." manage.py test temba/api temba/assets temba/campaigns
  temba/channels temba/contacts temba/flows temba/ivr temba/locations temba/msgs temba/orgs
  temba/public temba/reports temba/schedules temba/triggers temba/utils temba/values
  --verbosity=2 --noinput
after_success:
- coverage report -m --include="temba/api/*,temba/assets/*,temba/campaigns/*,temba/channels/*,temba/contacts/*,temba/flows/*,temba/ivr/*,temba/locations/*,temba/msgs/*,temba/orgs/*,temba/public/*,temba/reports/*,temba/schedules/*,temba/triggers/*,temba/utils/*,temba/values/*"
  --omit="*/migrations/*,*/tests" -i
- coveralls
notifications:
  slack:
    secure: YcjTz4XVOOj3iNy4dInO1zqAqD1rwpDtTlaMRJ0+C0sDwfK6n6jh9LK4cl7Rgx6CtLyob6bkytdlGu6RxeczM7GcYRSJua7MzJQXz6wL9bRsG6j2hqcIgd1JMR/Krx5qsU7kdWqcCFZ7C6oEokeeeeMMDXjHbyRJAcFhAou3oFyrRdCQSdx3hX5Tsq/GIbaiDWhTkpjVFYz9jEhuBnoyS1lLW/1HfiNDcBPDm4q5HvIUWAtpmUQOe9woikw3WUIZAQGPVI5nMQ9+JEZwQP/xIlmf2KCAn6v+UFN2CeymAFiU254xqIydVeZrXP7fnlPtoXk/UmdrPBlVgde//cHLXZMLI9sTeU1A4PfMTU9BC3je5mUAu/Ux9IL1YDDCu1ql1/QoMkA9EonTb4OciC0zhGqMQ1hxAKDLzAW5h+z0oU5tNk5Strlumlrmq7pZgvlL2b0u/I1y/yESuSJFUEmGGI8SG4bO+0U6l5QrYpU7gc8WNMOwCeyiasEFd9ahgJ9QDwJ5TIueTJ0VEzItGq7b/0GcZUsP6ke4ImxQZ2/HukrulZYO0dmyQI9w9T/BTsjxuFm3QIHG4ZjDvHQlUWo2yJ5/QjTysWe9aZE5RCPI5xrqeNUR4PKjbGSXR/GKTzURkGuSVfYvRy6ocLJT9nuNOq5pJE8XNr0R8kwmAXk6L9M=
